[package]
name = "hddmon-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name="hddmond"
path="./src/main.rs"

[dependencies]
async-std = "1.10.0"
hdd = "0.10.3"
